- name: Update packages, pacman config, and Install needed packages
  hosts: rpi4
  vars_files:
    - group_vars/common_pkgs.yml
  become: true
  tasks:

  - name: Print Distribution name
    debug:
      msg: Distribution "{{ ansible_distribution }}"
  
  - name: Configure multiple downloads for pacman
    blockinfile:
      block: |
        [options]
        ParallelDownloads=1

      path: /etc/pacman.conf
      backup: true
    tags: config
    when: ansible_distribution == 'Arch Linux'

  - name: Update Arch Linux packages
    community.general.pacman:
      update_cache: yes
      upgrade: yes
    tags: update
    when: ansible_distribution == 'Arch Linux'

  - name: Insall common Arch Linux packages
    community.general.pacman:
      pkg: "{{ pkgs }}"
      state: latest
      extra_args: --noconfirm --needed

  - name: Install Arch Linux packages
    community.general.pacman:
      pkg:
        - inetutils
        - git
        - python-pip
        - gcc
        - make
        - base-devel
        - i2c-tools
        - bash-completion
        - htop
        - zram-generator
        - cmake
        - core/man
        - pacman-contrib
        - aardvark-dns
        - btrfs-progs
        - raspberrypi-firmware
        - community/apcupsd
        - firewalld
        - community/motion
        - alsa-lib
        - extra/alsa-card-profiles
        - extra/alsa-plugins
        - extra/alsa-utils
        - extra/alsa-firmware
        - live-media
        - extra/gptfdisk
        - extra/pulseaudio-alsa
        - extra/lsof
        - usbutils
        # Needed for dig
        - extra/bind
      state: latest
      extra_args: --noconfirm --needed
    tags: alarm
    when: ansible_distribution == 'Arch Linux'

  - name: Install rpm fusion free
    dnf:
      name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      state: present
      disable_gpg_check: true
    when: ansible_distribution  == 'Fedora'

  - name: Install Fedora packages
    dnf:
      name:
        # Sound packages
        - alsa-firmware
        - alsa-lib
        - alsa-lib-devel
        - alsa-plugins-usbstream
        - alsa-plugins-pulseaudio
        - alsa-plugins-samplerate
        - alsa-plugins-upmix
        - alsa-tools
        - alsa-tools-firmware
        - motion
        - '@Development tools' 
        - motion
        # General Utilities
      state: latest
    when: ansible_distribution  == 'Fedora'
  
  - name: Install common Fedora packages
    dnf:
      name: "{{ pkgs }}"
      state: latest
    when: ansible_distribution  == 'Fedora'
  
  - name: Install dev packages
    dnf:
      name: "{{ dev_pkgs }}"
      state: latest
    when: ansible_distribution  == 'Fedora'
  

- name: Install util scripts
  hosts: rpi4
  vars_files:
    - group_vars/env.yml

  tasks:
    - name: Create ~/bin
      file:
        state: directory
        dest: "{{ user_home }}/bin"
        owner: "{{ user }}"
        group: "{{ user }}"
      tags: utils

    - name: Install shell scripts in ~/bin
      copy:
        src: "{{ item }}"
        dest: "{{ user_home }}/bin"
      with_fileglob: "templates/utils/*.sh"
      tags: utils
