- name: Update packages, pacman config, and Install needed packages
  hosts: rpi4
  become: true
  tasks:
  
  - name: Configure multiple downloads for pacman
    blockinfile:
      block: |
        [options]
        ParallelDownloads=1

      path: /etc/pacman.conf
      backup: true
    tags: config
    when: ansible_distribution == 'Arch Linux'

  - name: Update Arch Linux packages
    community.general.pacman:
      update_cache: yes
      upgrade: yes
    tags: update
    when: ansible_distribution == 'Arch Linux'

  - name: Install Arch Linux packages
    community.general.pacman:
      pkg:
        - vim
        - rsync
        - mdadm
        - inetutils
        - git
        - bc
        - python-pip
        - gcc
        - make
        - base-devel
        - i2c-tools
        - bash-completion
        - htop
        - zram-generator
        - cmake
        - core/man
        - pacman-contrib
        - podman
        - aardvark-dns
        - btrfs-progs
        - podman-docker
        - raspberrypi-firmware
        - screen
        - wget
        - community/apcupsd
        - firewalld
        - iotop
        - smartmontools
        - community/motion
        - alsa-lib
        - extra/alsa-utils
        - extra/alsa-firmware
        - extra/gptfdisk
        # Needed for dig
        - extra/bind
      state: latest
      extra_args: --noconfirm --needed
    tags: alarm
    when: ansible_distribution == 'Arch Linux'

  - name: Install rpm fusion free
    dnf:
      name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      state: present
      disable_gpg_check: true
    when: ansible_distribution  == 'Fedora'

  - name: Install Fedora packages
    dnf:
      name:
        # General Utilities
        - vim
        - rsync
        - mdadm
        - git
        - cmake
        - make
        - bc
        - podman
        - iotop
        - htop
        - smartmontools
        # Sound packages
        - alsa-firmware
        - alsa-lib
        - alsa-lib-devel
        - alsa-plugins-usbstream
        - alsa-plugins-pulseaudio
        - alsa-plugins-samplerate
        - alsa-plugins-upmix
        - alsa-tools
        - alsa-tools-firmware
        - motion
        - '@Development tools' 
        - motion
      state: latest
    when: ansible_distribution  == 'Fedora'

- name: Install util scripts
  hosts: rpi4
  vars_files:
    - group_vars/env.yml

  tasks:
    - name: Create ~/bin
      file:
        state: directory
        dest: "{{ user_home }}/bin"
        owner: "{{ user }}"
        group: "{{ user }}"
      tags: utils

    - name: Install shell scripts in ~/bin
      copy:
        src: "{{ item }}"
        dest: "{{ user_home }}/bin"
      with_fileglob: "templates/utils/*.sh"
      tags: utils
