- name: Secure fresh Arch Linux Arm Install
  hosts: rpi4
  vars_files:
    - group_vars/env.yml
  become: true

  tasks:
    - name: Install Raspberry linux kernel
      community.general.pacman:
        update_cache: yes
        pkg:
          - core/linux-rpi
          - core/linux-rpi-headers
          - alarm/firmware-raspberrypi
        extra_args: --needed
    
    - name: Reinstall raspberrypi-bootloader raspberrypi-firmware removed by rpi-linux install
      community.general.pacman:
        update_cache: no
        pkg:
          - raspberrypi-bootloader
          - raspberrypi-firmware

    # default rpi-linux package uses rootfstype=ext4, will cause boot failure when using btrfs filesystem
    - name: Install custom cmdline.txt
      copy:
        src: templates/system/boot/cmdline.txt
        dest: /boot/cmdline.txt
        owner: root
        group: root
    
    # Creates a backup regardless of file difference to the custom installed config files
    # Using this rather than backup: true because FAT32 doesn't support the backup filename of copy module
    - name: Backup config.txt and cmdline.txt
      shell:
        chdir: /root/boot/
        cmd: |
          cp /boot/config.txt config.txt_"$(date +%F-%T)"~
          cp /boot/cmdline.txt cmdline.txt_"$(date +%F-%T)"~
          chmod 0640 ./*.txt*~
