- name: Configure motion server
  hosts: rpi4
  vars:
    rtsp1:
      port: 8554
      name: frontdoor
      host: rpi0-frontdoor
      # Name for camera text and sub directory to save videos
    rtsp2:
      port: 8554
      name: driveway
      host: expresso
    rtsp3:
      port: 8554
      name: "{{ rtsp3name }}"
      host: rpi3
      # Name for camera text and sub directory to save videos
    motion_server:
      log_level: 6
      videos_dir: /data/motion
      video_length: 300
      video_quality: 100
      video_codec: mkv
      filename: "%Y:%m:%d-%H:%M:%S-%q"
      # converted to True, check that doesn't cause motion failure
      restrict_stream_localhost: true
      restrict_webcontrol_localhost: true
  become: true
  become_method: sudo

  tasks:
    - name: Get ipv4 address for rtsp cameras
      ansible.builtin.command: dig +short "{{ rtsp1.host }}"
      register: command_output
    - set_fact:
        rtsp1_ipv4: "{{ command_output.stdout }}"
      tags: cameras
    - name: Get "{{ rtsp2.host }}" address
      ansible.builtin.shell: "dig +short {{ rtsp2.host }} | tail -n 1"
      register: command_output
    - set_fact:
        rtsp2_ipv4: "{{ command_output.stdout }}"
      tags: cameras
    - name: Get "{{ rtsp3.host }}" address
      ansible.builtin.shell: "dig +short {{ rtsp3.host }} | tail -n 1"
      register: command_output
    - set_fact:
        rtsp3_ipv4: "{{ command_output.stdout }}"
      tags: cameras

    - name: Main motion config copy
      ansible.builtin.template:
        src: templates/motion/motion.conf.j2
        dest: /etc/motion/motion.conf
        mode: 0644
        owner: root
        group: root
        force: true
      tags: motion-conf

    - name: Create primary motion directory /data/motion
      ansible.builtin.file:
        path: /data/motion
        state: directory
        mode: 0750
        owner: motion
        group: video
      tags: dirs

    - name: Create "{{ rtsp1.name }}" motion directory in /data/motion
      ansible.builtin.file:
        path: "{{ motion_server.videos_dir }}/{{ rtsp1.name }}"
        state: directory
        mode: 0750
        owner: motion
        group: video
      tags: dirs

    - name: Create "{{ rtsp2.name }}" motion directory in /data/motion
      ansible.builtin.file:
        path: "{{ motion_server.videos_dir }}/{{ rtsp2.name }}"
        state: directory
        mode: 0750
        owner: motion
        group: video
      tags: dirs

    - name: Create "{{ rtsp3.name }}" motion directory in /data/motion
      ansible.builtin.file:
        path: "{{ motion_server.videos_dir }}/{{ rtsp3.name }}"
        state: directory
        mode: 0750
        owner: motion
        group: video
      tags: dirs

    - name: Camera1 motion config
      ansible.builtin.template:
        src: templates/motion/camera1.conf.j2
        dest: /etc/motion/camera1.conf
        mode: 0644
        owner: root
        group: root
        force: true
      tags: cameras

    - name: Camera2 motion config
      ansible.builtin.template:
        src: templates/motion/camera2.conf.j2
        dest: /etc/motion/camera2.conf
        mode: 0644
        owner: root
        group: root
        force: true
      tags: cameras

    - name: Camera3 motion config
      ansible.builtin.template:
        src: templates/motion/camera3.conf.j2
        dest: /etc/motion/camera3.conf
        mode: 0644
        owner: root
        group: root
        force: true
      tags: cameras

    - name: Start/Enable motion service
      ansible.builtin.systemd:
        name: motion
        state: restarted
        enabled: true
      tags: service cameras motion-conf
