- name: Mount disks needed for data storage
  hosts: rpi4
  vars:
    data_dir: /data
    backups_dir: /backups
    # first disk in btrfs raid10 with 4 disks in 5 disk moba usb device
    data_disc: "UUID=a46b9a52-ca9a-46fa-8e87-f5440f54a91e"
    backups_disc: "UUID=1847d7c9-17e7-4863-a1f7-f17aa06de7ff"
  vars_files:
    - group_vars/env.yml
  become: true

  tasks:
    - name: Make /data directory
      file:
        path: /data
        state: directory
        mode: '755'

    - name: Make /backups directory
      file:
        path: /backups/deja
        state: directory
        mode: '755'
    
    - name: Create user backups directory
      file:
        path: "/backups/deja/{{ hostname }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Add data Mount
      ansible.posix.mount:
        path: "{{ data_dir }}"
        src: "{{ data_disc }}"
        state: mounted
        fstype: btrfs
    - name: Add backup mount
      ansible.posix.mount:
        path: "{{ backups_dir }}"
        src: "{{ backups_disc }}"
        state: mounted
        fstype: btrfs
