- name: Setup v4l2rtspserver on Raspberry Pi OS
  hosts: rpi3
  vars:
    rtsp:
      url: "{{ bedroom2 }}"
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: Update apt cache then update all packages
      ansible.builtin.apt:
        update_cache: true
        name: "*"
        state: latest
      tags: update-pkgs

    - name: Install required packages and tools
      ansible.builtin.apt:
        pkg:
          # Debian 11 podman v3 is too old to build this Dockerfile
          - libv4l-0
          - libasound2
          - libasound2-plugin-equal
          # - liblivemedia77
          - liblog4cpp5v5
          - libasound2
          - libssl1.1
          - alsa-firmware-loaders
          - ca-certificates
          # Packages required for building from source
          - libasound2-dev
          - liblog4cpp5v5
          - liblog4cpp5-dev
          # Latest liblivemedia-dev will be cloned if missing
          # Later version than Debian Stable repo provides
          # - liblivemedia-dev
          - libv4l-dev
          - git
          - make
          - cmake
          - gcc
          - build-essential
          # Useful tools
          - vim
          - htop
          - alsa-tools
          - alsa-utils
      tags: install-pkgs

    - name: Remove unused dependencies
      ansible.builtin.apt:
        autoremove: true
      tags: update-pkgs install-pkgs

    - name: Git clone github.com/mpromonet/v4l2rtspserver
      ansible.builtin.git:
        repo: https://github.com/mpromonet/v4l2rtspserver.git
        dest: /tmp/v4l2rtspserver
        clone: true
        update: false
        version: v0.3.3

    - name: Build v4l2rtspserver from source and install
      ansible.builtin.shell: cmake . && make -j"$(nproc)" && make install
      args:
        chdir: /tmp/v4l2rtspserver
      register: build_output
      changed_when: false

    - ansible.builtin.debug: var=build_output.stdout_lines

    - name: Remove /tmp/v4l2rtspserver
      ansible.builtin.file:
        state: absent
        path: /tmp/v4l2rtspserver

    # TODO update this with template module, create template file, update readme with required vars
    # - name: Install custom v4l2rtspserver.service systemd unit
    #   ansible.builtin.copy:
    #     src: v4l2rtspserver.service
    #     dest: /usr/lib/systemd/system/v4l2rtspserver.service
    #     mode: 0644
    #   tags: update-config

    - name: Install v4l2rtspserver arguements to /usr/local/etc/v4l2rtspserver.env
      template:
        src: templates/rtsp/v4l2rtspserver.env.j2
        dest: /usr/local/etc/v4l2rtspserver.env
        mode: 0644
      tags: update-config

    - name: Enable v4l2rtspserver systemd unit
      ansible.builtin.systemd:
        name: v4l2rtspserver
        state: restarted
        enabled: true
        daemon_reload: true
      tags: update-config
