- name: Mount disks needed for data storage
  hosts: rpi4
  vars:
    data_dir: /data
    backup_dir: /backups
    # first disk in btrfs raid10 with 4 disks in 5 disk moba usb device
    data_disk: "UUID=9289fc29-6950-4a03-bc28-3f43acd2cbb6"
    backup_disk: "UUID=1847d7c9-17e7-4863-a1f7-f17aa06de7ff"
  vars_files:
    - group_vars/env.yml
  become: true

  tasks:
    - name: Make /data directory
      file:
        path: /data
        state: directory
        mode: '755'

    - name: Make /backups directory
      file:
        path: /backups/deja
        state: directory
        mode: '755'

    - name: Create user backups directory
      file:
        path: "/backups/deja/{{ backup_dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Add data Mount
      ansible.posix.mount:
        path: "{{ data_dir }}"
        src: "{{ data_disk }}"
        state: mounted
        fstype: btrfs
        opts: defaults,nofail
    - name: Add backup mount
      ansible.posix.mount:
        path: "{{ backup_dir }}"
        src: "{{ backup_disk }}"
        state: mounted
        fstype: btrfs
        opts: defaults,nofail
