# TODO setup name, hosts, and tasks sections
- name: Setup v4l2rtspserver podman container
  hosts:
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: Install Podman
      ansible.builtin.apt:
        name: podman
        state: present
      tags: container

    - name: Build v4l2rtspserver container image
      containers.podman.podman_image:
        build:
          extra_args: -f Dockerfile
          format: docker
        path: /tmp/v4l2rtspserver
        name: localhost/vmpromonet/v4l2rtspserver:latest
      tags: container

    - name: Create v4l2rtspserver container
      containers.podman.podman_container:
        name: v4l2rtspserver
        image: docker.io/mpromonet/v4l2rtspserver:latest-arm32v6
        command: -C1 -u "frontdoor"
        device: "/dev/video0"
        publish: "8554:8554/tcp"
        generate_systemd:
          new: yes
          path: /usr/lib/systemd/system/
          restart_policy: on-failure
        image_volume: tmpfs
        log_driver: journald
        log_level: info
      tags: container