---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.podman.io/driver: local
  creationTimestamp: "2023-02-03T20:20:35Z"
  name: pihole-log
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.podman.io/driver: local
  name: pihole-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pihole
  name: pihole
spec:
  automountServiceAccountToken: false
  containers:
  - env:
    - name: PROXY_LOCATION
      value: pihole
    - name: VIRTUAL_HOST
      value: pihole
    - name: ServerIP
      value: 10.50.0.2
    - name: TZ
      value: America/New_York
    - name: HOSTNAME
      value: pihole
    image: docker.io/pihole/pihole:latest
    name: pihole
    ports:
    - containerPort: 53
      hostPort: 53
      protocol: TCP
    - containerPort: 53
      hostPort: 53
      protocol: UDP
    - containerPort: 80
      hostPort: 8081
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/log/
      name: pihole-log-pvc
    - mountPath: /etc/pihole/
      name: pihole-config-pvc
  dnsConfig:
    nameservers:
    - 127.0.0.1
    - 1.1.1.1
  enableServiceLinks: false
  hostname: pi.hole
  volumes:
  - name: pihole-log-pvc
    persistentVolumeClaim:
      claimName: pihole-log
  - name: pihole-config-pvc
    persistentVolumeClaim:
      claimName: pihole-config


